### ISSUE TITLE
(This issue is a not real issue!)

### ISSUE THREAD

**Issue by sbrl** [justintroutman/pocketblock#2]
Pocketblock looks really good! After reading your first tutorial / guide, I feel that I actually understand pockenacci, and a little more about encryption in general. I'm looking forward to the next part in the series!

I've written a blog about it too, which you can find [here](https://starbeamrainbowlabs.com/blog/article.php?article=posts%2F192-Pocketblock.html).

**Comment by justintroutman** [comment]
A huge thanks for taking the time to write about it! The next module is underway, with some edits to the current one as well. Cheers!
